resilience4j:
  circuitbreaker:
    instances:
      inventoryBreak:
        registerHealthIndicator: true
        automaticTransationFromOpenToHalfOpenEnable: true
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        permittedNumberOfCalls: 5
        slidingWindowSize: 10
        waitDurationInOpenState: 10
        slidingWindowType: COUNT_BASE